spring:
  h2:
    console:
      settings:
        web-allow-others: false
      path: /h2
      enabled: true


  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop